version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  # create_infrastructure: 
  #   docker:
  #      - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:                      # create inventory file and add [all] so it can receive IPs from AWS command
  #         name: Create inventory file
  #         command: |
  #           mkdir project
  #           touch inventory
  #           echo [all] > project/inventory

  #     - run:                    # Fetch the EC2 public IPS for all instances with tag project:udacity and save it in project/inventory
  #         name: Save servers IPs in inventory
  #         command: |
  #           aws ec2 describe-instances \
  #           \
  #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
  #           --filters "Name=tag:Project,Values=udacity" \
  #           --output text >> project/inventory      
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1

  configure_infrastructure: 
  docker:
    - image: python:3.7-alpine3.11
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["cf:da:f8:77:c6:4f:7a:c3:11:50:ef:0b:2c:62:de:8c"] 
    - run:
        name: Install Ansible
        command: |
          apk add --update ansible
    - run:
        name: Run Playbook and Configure server
        command: |
          ansible-playbook -i inventory main.yml


  # Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure